[package]
name = "catlog"
description = "A toolbox for catgorical logic based on double theories"
authors = ["Evan Patterson"]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[features]
serde = ["dep:serde", "nonempty/serialize", "ustr/serde"]
serde-wasm = ["serde", "dep:wasm-bindgen", "dep:tsify-next"]

[dependencies]
archery = "1"
derivative = "2"
derive_more = { version = "1", features = ["from", "into"] }
<<<<<<< HEAD
either = "1"
=======
indoc = "2.0.5"
<<<<<<< HEAD
>>>>>>> 2dba867 (basic math expression compiler + evaluator)
=======
nalgebra = "^0.32.3"                                                 # specific version to be compatible with ode_solvers
>>>>>>> 00338d3 (solve ODEs from user-provided expressions)
nonempty = "0.10"
ode_solvers = "0.4.0"
ref-cast = "1"
serde = { version = "1", features = ["derive"], optional = true }
textplots = "0.8.6"
thiserror = "1"
tsify-next = { version = "0.5", features = ["js"], optional = true }
ustr = "1"
wasm-bindgen = { version = "0.2.92", optional = true }
